import { z } from "genkit";
export const IssueTypeEnum = z
  .enum([
    "SECURITY",
    "PERFORMANCE",
    "READABILITY",
    "BUG",
    "STYLE",
    "BEST_PRACTICE",
    "TYPO",
    "OTHER",
  ])
  .describe("Type of the issue identified in the suggestion.");

// Suggestion schema
export const SuggestionSchema = z.object({
  fileName: z
    .string()
    .describe("The name of the file the suggestion applies to."),
  suggestionText: z.string().describe("The suggestion for improvement."),
  lineNumber: z.any().optional().describe("Line number in the new file"),
  type: IssueTypeEnum.optional(),
});

/**
 * Defines the severity levels for a code review suggestion.
 */
export const SeverityTypeEnum = z
  .enum(["INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL"])
  .describe("Severity of the issue identified.");

export const CodeReviewerInputSchema = z.object({
  owner: z.string(),
  repo: z.string(),
  pull_number: z.number(),
  language: z.string(),
  focusAreas: z.string().optional(),
});
/**
 * The main schema for the final output of the code review process.
 */
export const CodeReviewResultSchema = z.object({
  summary: z
    .string()
    .describe("A concise summary of the code review findings."),
  suggestions: z
    .array(
      z.object({
        fileName: z
          .string()
          .describe(
            "The name of the file the suggestion applies to (e.g., 'src/main.py')."
          ),
        suggestionText: z.string().describe("The suggestion for improvement."),
        lineNumber: z
          .any()
          .optional()
          .describe(
            "Optional line number in the NEW file where the suggestion applies, if relevant."
          ),

        type: IssueTypeEnum.optional(),

        // severity: SeverityTypeEnum.optional(),
      })
    )
    .describe("An itemized list of specific suggestions for improvement."),
  parsedDiff: z
    .any()
    .optional()
    .describe(
      "The raw PR diff content that was reviewed. This is added back by the flow, not generated by the LLM."
    ),
  message: z
    .string()
    .optional()
    .describe("A general message about the review process."),
});
export const PostPRCommentsInputSchema = z.object({
  owner: z.string().describe("Repository owner (e.g., 'octocat')"),
  repo: z.string().describe("Repository name (e.g., 'Spoon-Knife')"),
  pull_number: z.number().describe("Pull request number"),
  suggestions: z
    .array(SuggestionSchema)
    .describe("An array of suggestions to be posted as comments on the PR."),
  postAsSingleComment: z
    .boolean()
    .optional()
    .default(true)
    .describe("If true, all suggestions are combined into one comment."),
});
export const PostPRCommentOutputSchema = z.object({
  success: z.boolean(),
  message: z.string(),
  commentsPostedCount: z.number(),
  failedCommentsCount: z.number(),
  commentUrls: z.array(z.string()).optional(),
});

// Define input schema (No changes here)
export const CodeReviewInputSchema = z.object({
  code: z.string().describe("The code snippet to review"),
  language: z.string().describe("Programming language of the code"),
  focusAreas: z
    .string()
    .optional()
    .describe(
      "Specific areas to focus on (e.g., security, performance, readability)"
    ),
});

export const CodeReviewOutputSchema = z.object({
  summary: z.string().describe("General feedback summary"),
  suggestions: z.array(z.string()).describe("List of suggested improvements"),
  // MODIFIED: Updated the description to be more specific
  suggestions_summary: z
    .string()
    .describe(
      "A conversational paragraph that first summarizes the code's purpose and then outlines the suggestions. Suitable for text-to-speech."
    ),
  correctedCode: z
    .string()
    .describe(
      "The revised version of the input code with inline comments explaining changes"
    ),
});

export const RefactorFileInputSchema = z.object({
  owner: z.string().describe("Repository owner"),
  repo: z.string().describe("Repository name"),
  pull_number: z.number().describe("The pull request number"),
  path: z.string().describe("Path to the file to refactor"),
  suggestions: z
    .array(z.string())
    .describe("A list of suggestions from the code review to apply."),
  language: z.string().describe("The programming language of the file."),
});

// Define the output schema for this prompt
export const RefactorFileOutputSchema = z.object({
  originalContent: z.string().describe("The original content of the file."),
  refactoredContent: z
    .string()
    .describe("The content of the file after refactoring."),
  diff: z.string().describe("The unified diff string showing the changes."),
  message: z
    .string()
    .describe("A summary message about the refactoring process."),
});
// --- NEW Schemas for the dedicated refactor agent ---
export const CodeRefactorInputSchema = z.object({
  fileName: z.string().describe("The name/path of the file being refactored."),
  originalContent: z
    .string()
    .describe("The entire original source code of the file."),
  suggestions: z
    .array(z.string())
    .describe("A list of natural language suggestions to apply to the code."),
  language: z.string().describe("The programming language of the code."),
});

export const CodeRefactorOutputSchema = z.object({
  refactoredContent: z
    .string()
    .describe(
      "The complete, final source code for the file after all suggestions have been applied."
    ),
  diff: z
    .string()
    .describe(
      "The unified diff string showing the changes between original and refactored code."
    ),
  message: z
    .string()
    .describe("A summary message about the refactoring process."),
});
