include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.g.dart #Exclude generated files
  errors:
    invalid_assignment: error
    missing_return: error

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    unnecessary_const: true
    use_key_in_widget_constructors: true
    always_put_required_named_parameters_first: true
    sized_box_for_whitespace: true
    prefer_if_null_operators: true
    avoid_function_literals_in_foreach_calls: true
    unnecessary_null_checks: true
    cascade_invocations: true
    prefer_final_locals: true
#Enable certain lints as needed or disable them if conflicting with project requirements
