// flows/prReviewFlow.js
import { ai } from "../ai.js";
import { z } from "genkit";
import { fetchPRDiffTool } from "../tools/github_tools.js";
import { gemini20Flash } from "@genkit-ai/googleai";
import parseDiff from "parse-diff";

// --- Schemas ---

// This schema is now for the LLM's INPUT, focusing on contextual diff content.
const FileDiffSchema = z.object({
  filePath: z
    .string()
    .describe("Path of the file that was changed (e.g., 'src/index.js')."),
  diffContent: z
    .string()
    .describe(
      "The unified diff content for the file, including '+', '-', and context lines."
    ),
});

const IssueTypeEnum = z
  .enum([
    "SECURITY",
    "PERFORMANCE",
    "READABILITY",
    "BUG",
    "STYLE",
    "BEST_PRACTICE",
    "TYPO",
    "OTHER",
  ])
  .describe("Type of the issue identified in the suggestion.");

const SeverityTypeEnum = z
  .enum(["INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL"])
  .describe("Type of the issue identified in the suggestion.");

const CodeReviewResultSchema = z.object({
  summary: z
    .string()
    .describe("A concise summary of the code review findings."),
  suggestions: z
    .array(
      z.object({
        fileName: z
          .string()
          .describe(
            "The name of the file the suggestion applies to (e.g., 'src/main.py')."
          ),
        suggestionText: z.string().describe("The suggestion for improvement."),
        lineNumber: z
          .number()
          .optional()
          .describe(
            "Optional line number in the NEW file where the suggestion applies, if relevant."
          ),
        type: IssueTypeEnum.optional(),
        severity: SeverityTypeEnum.optional(),
      })
    )
    .describe(
      "An itemized list of specific suggestions for improvement with file names, optional line numbers, and type/severity."
    ),
  parsedDiff: z
    .any()
    .describe(
      "The raw PR diff content that was reviewed. This is added back by the flow, not generated by the LLM."
    ),
  message: z
    .string()
    .optional()
    .describe("A general message about the review process."),
});

// --- Flow Definition ---

export const prReviewFlow = ai.defineFlow(
  {
    name: "prReviewFlow",
    inputSchema: z.object({
      owner: z.string().describe("Repository owner (e.g., 'octocat')"),
      repo: z.string().describe("Repository name (e.g., 'Spoon-Knife')"),
      pull_number: z.number().describe("Pull request number"),
      language: z
        .string()
        .describe(
          "Programming language of the code to review (e.g., 'JavaScript', 'Python')"
        ),
      focusAreas: z
        .string()
        .optional()
        .describe(
          "Optional areas to focus on (e.g., 'security', 'performance')"
        ),
    }),
    outputSchema: CodeReviewResultSchema,
  },
  async (input) => {
    try {
      // 1. Fetch the raw PR diff content
      const rawDiffContent = await fetchPRDiffTool({
        owner: input.owner,
        repo: input.repo,
        pull_number: input.pull_number,
      });

      if (!rawDiffContent) {
        throw new Error(
          "Failed to fetch PR diff: Diff content was empty or null."
        );
      }

      // 2. Parse the raw diff into a contextual format for the LLM
      const files = parseDiff(rawDiffContent);
      const parsedDiffForLLM = files
        .map((file) => {
          const filePath = file.to || file.from || "unknown";

          // Create a string that represents the diff chunks for better context
          const diffContent = file.chunks
            .map((chunk) => {
              // Recreate the diff chunk view by joining all changes.
              // This gives the LLM full context.
              return chunk.changes.map((change) => change.content).join("\n");
            })
            .join("\n\n"); // Separate chunks with a blank line

          if (!diffContent.trim()) return null; // Skip files with no changes

          return {
            filePath,
            diffContent,
          };
        })
        .filter(Boolean); // Filter out any null entries (files with no changes)

      if (parsedDiffForLLM.length === 0) {
        return {
          summary: "No code changes found to review.",
          suggestions: [],
          parsedDiff: rawDiffContent,
          message:
            "The PR diff appears to be empty or contains no code changes.",
        };
      }

      // 3. Generate the updated prompt for the LLM
      const prompt = `You are an expert ${
        input.language
      } code reviewer. Your task is to analyze the provided code diff and identify potential issues.

🚨 ***CRITICAL INSTRUCTIONS:*** 🚨

1.  **FOCUS ON ADDED CODE**: The diff for each file will be provided. Lines starting with \`+\` are additions, lines with \`-\` are deletions. **Your review and suggestions must focus on the ADDED lines (\`+\`).** Do NOT suggest changes for deleted code (\`-\`). Use the surrounding code only for context.
2.  **IGNORE NO-ISSUE FILES**: If a file's changes are correct and have no issues, do NOT mention it in your suggestions. Your output should only contain suggestions for files that need improvement.
3.  **MANDATORY FIELDS**: For **every single suggestion**, you MUST provide a "type" and a "severity".
4.  **ACCURATE LINE NUMBERS**: Line numbers must refer to the position in the NEW version of the file.

📌 **Allowed 'type' values**:
- 'SECURITY', 'PERFORMANCE', 'READABILITY', 'BUG', 'STYLE', 'BEST_PRACTICE', 'TYPO', 'OTHER'

📌 **Allowed 'severity' values**:
- 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'

---

📦 **Provide your output in the following strict JSON format**:

\\\json
{
  "summary": "A concise overview of your key findings.",
  "suggestions": [
    {
      "fileName": "path/to/file.js",
      "suggestionText": "Precise, actionable feedback for an added line.",
      "lineNumber": 123,
      "type": "READABILITY",
      "severity": "MEDIUM"
    }
  ]
}
\\\

---

Here is the code diff to review:
${JSON.stringify(parsedDiffForLLM, null, 2)}

** Don't give review based on ** - **Deleted Content, you can use that as context but please focus on ** + ** lines as they are the actual code.**
🔍 Review the added code carefully.
Be critical, accurate, and helpful — this review will guide automated refactoring and real code updates. Do not make up line numbers or vague comments. If a change is correct and well-written, note that positively with an 'INFO'-level suggestion.

You are expected to perform like a senior engineer reviewing code in a mission-critical system.`;

      // 4. Send to LLM for review
      const aiResponse = await ai.generate({
        model: gemini20Flash,
        prompt,
        output: {
          format: "json",
          schema: z.object({
            summary: CodeReviewResultSchema.shape.summary,
            suggestions: CodeReviewResultSchema.shape.suggestions,
          }),
        },
      });

      const output = aiResponse.output;

      if (!output) {
        throw new Error("Model returned null or malformed output.");
      }

      // 5. Return the structured results
      return {
        summary: output.summary,
        suggestions: output.suggestions,
        parsedDiff: rawDiffContent,
        message: "PR review completed successfully.",
      };
    } catch (error) {
      console.error("PR Review Flow Error:", error);
      const errorMessage = `PR review failed: ${error.message}`;

      return {
        summary: "Review failed.",
        suggestions: [],
        parsedDiff: "[]",
        message: errorMessage,
      };
    }
  }
);
