// flows/prReviewFlow.js
import { ai } from "../ai.js";
import { z } from "genkit";
import { fetchPRDiffTool } from "../tools/github_tools.js";
import { gemini20Flash } from "@genkit-ai/googleai";
import parseDiff from "parse-diff";

// --- Schemas ---

// Schema for a single file's changes within the parsed diff
// This schema is used for what you prepare to SEND to the LLM.
const FileDiffSchema = z.object({
  filePath: z
    .string()
    .describe("Path of the file that was changed (e.g., 'src/index.js')."),
  addedLines: z
    .array(z.string())
    .describe("Lines added in this file (without '+ ' prefix)."),
  deletedLines: z
    .array(z.string())
    .describe("Lines deleted in this file (without '- ' prefix)."),
});

// Define the IssueTypeEnum for consistency
const IssueTypeEnum = z
  .enum([
    "SECURITY",
    "PERFORMANCE",
    "READABILITY",
    "BUG",
    "STYLE",
    "BEST_PRACTICE",
    "TYPO",
    "OTHER",
  ])
  .describe("Type of the issue identified in the suggestion.");

// Define the IssueTypeEnum for consistency
const SeverityTypeEnum = z
  .enum(["INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL"])
  .describe("Type of the issue identified in the suggestion.");

// Overall schema for the structured code review result that your FLOW RETURNS.
// The LLM will only generate summary and suggestions.
const CodeReviewResultSchema = z.object({
  summary: z
    .string()
    .describe("A concise summary of the code review findings."),
  suggestions: z
    .array(
      z.object({
        fileName: z
          .string()
          .describe(
            "The name of the file the suggestion applies to (e.g., 'src/main.py')."
          ),
        suggestionText: z.string().describe("The suggestion for improvement."),
        lineNumber: z
          .number()
          .optional()
          .describe(
            "Optional line number in the NEW file where the suggestion applies, if relevant."
          ),
        // --- NEW FIELD FOR CHARTING ---
        type: IssueTypeEnum.optional(), // Make type optional in case LLM misses it sometimes
        // --- NEW FIELD FOR CHARTING ---
        severity: SeverityTypeEnum.optional(), // Add severity for charting
      })
    )
    .describe(
      "An itemized list of specific suggestions for improvement with file names, optional line numbers, and type/severity."
    ),
  // The 'parsedDiff' in the FINAL output of the flow is the raw content you fetched.
  // It's not something the LLM generates; your flow adds it back.
  // Keep it here as you had it in the output schema.
  parsedDiff: z
    .any()
    .describe(
      "The raw PR diff content that was reviewed. This is added back by the flow, not generated by the LLM."
    ),
  message: z
    .string()
    .optional()
    .describe("A general message about the review process."),
});

// --- Flow Definition ---

export const prReviewFlow = ai.defineFlow(
  {
    name: "prReviewFlow",
    inputSchema: z.object({
      owner: z.string().describe("Repository owner (e.g., 'octocat')"),
      repo: z.string().describe("Repository name (e.g., 'Spoon-Knife')"),
      pull_number: z.number().describe("Pull request number"),
      language: z
        .string()
        .describe(
          "Programming language of the code to review (e.g., 'JavaScript', 'Python')"
        ),
      focusAreas: z
        .string()
        .optional()
        .describe(
          "Optional areas to focus on (e.g., 'security', 'performance')"
        ),
    }),
    // The outputSchema here applies to the *overall flow return*.
    outputSchema: CodeReviewResultSchema,
  },
  async (input) => {
    try {
      // 1. Fetch the raw PR diff content
      const rawDiffContent = await fetchPRDiffTool({
        owner: input.owner,
        repo: input.repo,
        pull_number: input.pull_number,
      });

      if (!rawDiffContent) {
        throw new Error(
          "Failed to fetch PR diff: Diff content was empty or null."
        );
      }

      // 2. Parse the raw diff content into your desired structured format
      const files = parseDiff(rawDiffContent);
      const parsedDiffForLLM = files.map((file) => {
        const filePath = file.to || file.from || "unknown";

        const addedLines = [];
        const deletedLines = [];

        if (file.chunks) {
          file.chunks.forEach((chunk) => {
            chunk.changes.forEach((change) => {
              if (change.type === "add") {
                addedLines.push(
                  change.content.startsWith("+")
                    ? change.content.substring(1)
                    : change.content
                );
              } else if (change.type === "del") {
                deletedLines.push(
                  change.content.startsWith("-")
                    ? change.content.substring(1)
                    : change.content
                );
              }
            });
          });
        }
        return {
          filePath,
          addedLines,
          deletedLines,
        };
      });

      // 3. Generate the prompt for the LLM
      const prompt = ` You are an expert and meticulous code reviewer with deep knowledge of ${
        input.language
      }. Your role is to **analyze every single change in the provided code diff** and provide a **thorough, high-quality review**.

Your focus should include (but is not limited to):
${
  input.focusAreas ||
  "- General best practices\n- Code correctness and logic errors\n- Security vulnerabilities\n- Performance pitfalls\n- Code style and maintainability"
}

---

🚨 ***STRICT INSTRUCTIONS:*** 🚨

For **every single suggestion**, you MUST include both:
- A valid "type" (from the allowed list)
- A valid "severity" (from the allowed list)

🧠 DO NOT skip or combine unrelated issues. Each issue must be listed as a separate suggestion with correct line number and context.

📌 **Allowed 'type' values** (choose exactly one):
- 'SECURITY' — insecure handling of user input, secrets, or system resources
- 'PERFORMANCE' — inefficient operations, resource leaks, unnecessary computation
- 'READABILITY' — hard-to-understand code, poor naming, unclear logic
- 'BUG' — incorrect behavior, logical flaws, edge case failures
- 'STYLE' — formatting, indentation, lint rule violations
- 'BEST_PRACTICE' — non-idiomatic usage, poor architectural patterns
- 'TYPO' — spelling or grammar errors
- 'OTHER' — if it doesn’t fit any of the above types

📌 **Allowed 'severity' values**:
- 'CRITICAL' — must-fix issues (crash/data loss/security breach)
- 'HIGH' — serious risk or flaw needing quick attention
- 'MEDIUM' — moderate importance; improves quality or robustness
- 'LOW' — minor fix; good to have but not urgent
- 'INFO' — observation, comment, or praise

---

📦 **Provide your output in the following strict JSON format**:

\\\json
{
  "summary": "A concise overview of your key findings.",
  "suggestions": [
    {
      "fileName": "path/to/file.js",
      "suggestionText": "Precise, actionable feedback that a developer can understand and implement.",
      "lineNumber": 123,
      "type": "READABILITY", 
      "severity": "MEDIUM"
    }
  ],
  "message": "Optional high-level note about the review, e.g., next steps or general feedback."
}
\\\

---

Here is the code diff to review:
${rawDiffContent}

🔍 Review each file and line carefully. Be critical, accurate, and helpful — this review will guide automated refactoring and real code updates. Do not make up line numbers or vague comments. If a change is correct and well-written, note that positively with an 'INFO'-level suggestion.

You are expected to perform like a senior engineer reviewing code in a mission-critical system.
;
`;
      // 4. Send to LLM for review
      const aiResponse = await ai.generate({
        model: gemini20Flash,
        prompt,
        output: {
          format: "json",

          schema: z.object({
            summary: CodeReviewResultSchema.shape.summary,
            suggestions: CodeReviewResultSchema.shape.suggestions,
            message: CodeReviewResultSchema.shape.message,
          }),
        },
      });

      const output = aiResponse.output;

      if (!output) {
        throw new Error(
          "Model returned null or malformed output after Genkit's validation."
        );
      }

      // 5. Return the structured results, adding back the rawDiffContent
      return {
        summary: output.summary,
        suggestions: output.suggestions,
        parsedDiff: rawDiffContent, // This is added back by your flow, not generated by the LLM
        message: output.message || "PR review completed successfully.",
      };
    } catch (error) {
      console.error("PR Review Flow Error:", error);
      let errorMessage = "An unexpected error occurred during PR review.";
      if (error.message && error.message.includes("Schema validation failed")) {
        errorMessage = ` Schema validation failed for AI model output. This often means the AI did not return the expected JSON format. Details: ${error.message}`;
      } else {
        errorMessage = `PR review failed: ${error.message}`;
      }

      // Ensure the error return matches the overall CodeReviewResultSchema for consistency
      return {
        summary: `Review failed: ${errorMessage}`,
        suggestions: [],
        parsedDiff: "[]", // Return empty string or appropriate value for raw diff on failure
        message: errorMessage,
      };
    }
  }
);
